### ISSUE TITLE
parsePath doesn't return an exact match of paths with large curves

### ISSUE THREAD

**Issue by NathanSaunders01** [wcandillon/react-native-redash#101]
Issue: 
parsePath doesn't return an exact match of my path which causes getPointAtLength to return inaccurate values.

Versions:
react-native-redash: 8.0.0

Description: 

I'm building a line graph similar to revolut's which uses a gestureHandler to navigate it and uses d3 to create the SVG.

In my cursor component, I read the translateX value to map the cursor onto the line graph.

When I compare to svg-path-properties's path properties, I see that it returns a shorter total length than the parsePath function does in redash. 

This is the example path with large curves below.

`path = "M0,106.2L6.578947368421052,100.8C13.157894736842104,95.40000000000002,26.31578947368421,84.60000000000001,39.473684210526315,90.60000000000001C52.63157894736842,96.60000000000001,65.78947368421052,119.39999999999999,78.94736842105263,109.19999999999999C92.10526315789474,99,105.26315789473684,55.79999999999999,118.42105263157896,56.099999999999994C131.57894736842104,56.4,144.73684210526315,100.2,157.89473684210526,119.10000000000001C171.05263157894737,138,184.21052631578945,132,197.36842105263156,110.7C210.52631578947367,89.39999999999999,223.68421052631575,52.79999999999999,236.8421052631579,58.49999999999999C250,64.19999999999999,263.15789473684214,112.19999999999999,276.3157894736842,129C289.4736842105263,145.79999999999998,302.6315789473684,131.4,315.7894736842105,132.3C328.94736842105266,133.20000000000002,342.10526315789474,149.4,355.2631578947368,156.29999999999998C368.4210526315789,163.20000000000002,381.57894736842104,160.79999999999998,394.7368421052631,136.20000000000002C407.89473684210526,111.60000000000001,421.05263157894734,64.8,434.2105263157894,39C447.3684210526316,13.199999999999998,460.5263157894737,8.399999999999997,473.6842105263158,15.899999999999997C486.8421052631579,23.399999999999995,500,43.199999999999996,513.1578947368421,66.60000000000001C526.3157894736842,90,539.4736842105264,117,552.6315789473684,117C565.7894736842105,117,578.9473684210526,90,592.1052631578947,78C605.2631578947369,66,618.421052631579,69,631.5789473684212,58.5C644.7368421052632,48,657.8947368421053,24,671.0526315789474,12.6C684.2105263157895,1.1999999999999982,697.3684210526316,2.3999999999999964,710.5263157894736,5.999999999999996C723.6842105263158,9.599999999999994,736.8421052631579,15.599999999999994,743.4210526315788,18.599999999999994L750,21.599999999999994"`

Here is the code in the cursor component:

```
export default ({ d, r, borderWidth, borderColor, transX }: CursorProps) => {
  const radius = r + borderWidth / 2;
  const path = parsePath(d);
  const length = interpolate(transX, {
    inputRange: [0, width],
    outputRange: [0, -path.totalLength]
  });
  const { y, x } = getPointAtLength(path, length);
// I divide x by 2 because the graph is width*2 but the cursor moved from 0 to width
  const translateX: any = sub(divide(x, 2), radius);
  const translateY: any = sub(y, radius);
  return (
    <Animated.View
      style={{
        transform: [{ translateX }, { translateY }],
        width: radius * 2,
        height: radius * 2,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute"
      }}
    >
      <View
        style={{
          width: radius * 2,
          height: radius * 2,
          borderRadius: radius,
          borderColor,
          borderWidth,
          backgroundColor: white
        }}
      />
    </Animated.View>
  );
};
```

**Comment by NathanSaunders01** [comment]
The issue is not with the function but with my calculations...

**Comment by ducbka02** [comment]
@NathanSaunders01 How do you get exact coordinate of asixY from axis X in case?
