### ISSUE TITLE
useTransition() and react-native life cycles

### ISSUE THREAD

**Issue by lucaspelloni2** [wcandillon/react-native-redash#115]
Hi all, 

I tried to remove the initial animation coming from `useTransition` once the component gets rendered for the first time. 

I *hacked* it  by introducing a flat to state weather the component has been mounted yet or not.

```
    const transition = useTransition(
      animatedValue,
      !isMounted ? animatedValue : not(animatedValue),
      animatedValue,
      200,
      Easing.ease,
    );
```

Basically, if the component is not mounted the transition goes from 1 to 1 resulting in a non visibile effect in the animation. Otherwise, it goes from 1 to 0 and so it performs a transition (based on the animated value).
This works well in modern devices and in production. However, I am getting some issues in debug mode with old phones. I think there might be a cleaner approach. 

Are you experiencing something similar? If yes, what is your approach to avoid the initial animation?

**Comment by wcandillon** [comment]
@lucaspelloni2 Thank you so much for reporting this :) The implementation was broken, it should be fixed now. Sorry for the inconvenience please reopen if the issue is not fixed.
