### ISSUE TITLE
minor typo in readme (parenthesis missing)

### ISSUE THREAD

**Issue by tkreis** [wcandillon/react-native-redash#130]
It seems like a Parenthesis went missing in the docs:
https://github.com/wcandillon/react-native-redash/blob/master/README.md#loop-clock-clock-duration-node-easing-easingfunction-boomerang--false-autostart--true-
`set(animation, runLoop(400, Easing.linear);` 
and it should be 
`  set(animation, runLoop(400, Easing.linear));`

**Comment by felippepuhle** [comment]
We can close this, it's already fixed
