### ISSUE TITLE
runTiming is not a function

### ISSUE THREAD

**Issue by JherysVargas** [wcandillon/react-native-redash#131]
Get the following error when you imported runTiming
![image](https://user-images.githubusercontent.com/39938693/70819076-4c961380-1da3-11ea-9810-b817abb964d2.png)

**Comment by afshawnlotfi** [comment]
Having the same problem. I switched to version 4.0.0 and it worked

**Comment by wcandillon** [comment]
Newer version of redash have a function named `timing()` instead. I hope this helps.

**Comment by DovletAmanov** [comment]
I am facing the same error for "withTimingTransition()"

**Comment by DovletAmanov** [comment]
When I removed "node_modules, package-lock.json" and "build folder, Pods, Podfile.lock" in iOS and installed again, error went away, hope it will work for you too :)

**Comment by tanviagwl98** [comment]
I am having this issue with **useTransition()**, please help me if anybody has solved this issue
[
![image](https://user-images.githubusercontent.com/45534001/102351183-08e47400-3fcc-11eb-8eeb-761b9b8784eb.png)
](url)

**Comment by victorbruce** [comment]
@tanviagwl98 Try importing the function this way: ```import {useTransition} from 'react-native-redash/lib/module/v1'```

**Comment by tanviagwl98** [comment]
> @tanviagwl98 Try importing the function this way: `import {useTransition} from 'react-native-redash/lib/module/v1'`

Thank you @victorbruce , I have resolved my issue.

**Comment by quicksilverr** [comment]
> Newer version of redash have a function named `timing()` instead. I hope this helps.

There isn't timing now, please can you point us to which to use now?

**Comment by mtoninelli** [comment]
same here... I can't find any doc about it
