### ISSUE TITLE
Low FPS onScroll

### ISSUE THREAD

**Issue by mikikanez** [wcandillon/react-native-redash#138]
Hi everyone! 

I have a problem with onScroll function (I guess...)

The title animation looks glichy or low FPS. The performance is 60FPS all time, but it looks weird. Only on iOS Expo simulator. On Android works fine. This is the interpolation constant:

`        const scale = interpolate(y, {
            inputRange: [-height, 0],
            outputRange: [10, 1],
            extrapolateRight: Extrapolate.CLAMP
        })
`

And this is the rener function:

`
    renderList = (y) =>{
        const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);
        return(
            <AnimatedFlatList onScroll={ onScroll({y}) } style={{paddingTop:10}} keyExtractor={this.keyExtractor} data={events} renderItem={({ item }) => <Event data={item} />}/>
        )
    }
`

![ezgif com-resize](https://user-images.githubusercontent.com/46752328/71254235-a0b47100-232a-11ea-8bd4-8f5a9b5fdfa7.gif)

Sorry for the GIF quality...

Thank you!

**Comment by dsznajder** [comment]
@mikikanez Could you share whole component with header? Also, you can try add `scrollEventThrottle={16}` to `AnimatedFlatList`

**Comment by mikikanez** [comment]
It worked with `scrollEventThrottle={16}`!! Amazing!

Thank you very very much! 👍
