### ISSUE TITLE
useValues with Clock

### ISSUE THREAD

**Issue by gp3gp3gp3** [wcandillon/react-native-redash#158]
👋

I was looking to replace my `useMemoOne` calls with the `useValues` or `useNamedValues` helper functions, but it looks like it only takes primitive values and returns the animated values.  Is there a way to memoize `new Clock()` variables with this helper function, or is that a feature that could be added somehow?  Unless `clocks` do not need to be memoized and can be recreated in the render calls?

Not sure how this API would adjust, maybe passed a clock type?
```
const [clock] = useValues([Clock], [])
```

Thanks for this wonderful library!  👍

**Comment by wcandillon** [comment]
That's a good feature request, we should have useClocks()

**Comment by Guuz** [comment]
@wcandillon FYI: The documentation for this new function is missing. Took me quite a while to find it :)

**Comment by scottarnold** [comment]
I'll update the docs for this 😇
