### ISSUE TITLE
rgbToHsv() used by interpolateColors not passing correct hue to colorHSV()

### ISSUE THREAD

**Issue by jordanbb** [wcandillon/react-native-redash#16]
The colorHSV function expects the h (hue) value to be a value between 0 and 360. However, the value rgbToHsv outputs for h is a decimal. According to [this stackoverflow](https://stackoverflow.com/questions/8022885/rgb-to-hsv-color-in-javascript) h needs to be  multiplied by 360. Something like this:

```
const rgbToHsv = (c: RGBColor) => {
  const r = c.r / 255;
  const g = c.g / 255;
  const b = c.b / 255;

  const ma = Math.max(r, g, b);
  const mi = Math.min(r, g, b);
  let h: number = 0;
  const v = ma;

  const d = ma - mi;
  const s = ma === 0 ? 0 : d / ma;
  if (ma === mi) {
    h = 0; // achromatic
  } else {
    switch (ma) {
    case r: h = (g - b) / d + (g < b ? 6 : 0); break;
    case g: h = (b - r) / d + 2; break;
    case b: h = (r - g) / d + 4; break;
    default: // do nothing
    }
    h /= 6;
  }
  return { h: Math.round(h * 360), s, v };
};
```
patching the rgbToHsv function to the this code appears to have corrected the issue.

**Comment by wcandillon** [comment]
Thks a lot! I didn't catch this bug probably because I was only interpolating on the gray scale.

**Comment by wcandillon** [comment]
I tried your fix and it works great big thank you 🙌🏻
