### ISSUE TITLE
Allow initial values for withSpringTransitions

### ISSUE THREAD

**Issue by tiagobnobrega** [wcandillon/react-native-redash#160]
Hi... I'm new to this lib (and react-native animation in general), so excuse if I make any rookie mistake. The _withSpringTransition_ functions presume the initial value is zero. This is generally a great assumption, and basically You can derive any value from this, by treating it as a "progress" delta, but I think It would be nice to override this, by allowing an initial value. 

A use case for this could be expanding a view width/height, something like: 

```javascript
const width = withSpringTransition(WINDOW_WIDTH, {initialValue: new Value(elementInitialWidth)});
const height = withSpringTransition(WINDOW_HEIGHT/2, {initialValue: new Value(elementInitialHeight)})
```
I realize this would lead to starting 2 different Clocks, and I'm not sure if this is the best practice. But from a user point of view, seems like a nice feature to have. Anyway, please let me know what You think about it.

**Comment by dsznajder** [comment]
@tiagobnobrega I would go for interpolating transition value. You can create just one i.e.
```js
const transition = useTimingTransition(visible)

const width = interpolate(transition, { inputRange: [0,1], outputRange: [20, 40])
const height = interpolate(transition, { inputRange: [0,1], outputRange: [40, 80])
```

Additionally you have `bInterpolate` inside this package so:

```js
const transition = useTimingTransition(visible)

const width = bInterpolate(transition, 20, 40)
const height = interpolate(transition, 40, 80)
```

**Comment by wcandillon** [comment]
Right now the transition always goes from 0 to 1 where 0 means the transition is starting and 1 means that the transition is over. Closing for now but please feel free to re-open if there are use cases that I'm missing.

**Comment by tiagobnobrega** [comment]
@dsznajder I see what You mean... Thanks!
