### ISSUE TITLE
ReText not documented

### ISSUE THREAD

**Issue by arberK** [wcandillon/react-native-redash#170]
Hi @wcandillon , 

could you please document ReText in the new documentation. Is this an utility component, equivalent to setting nativeProps to TextInput,  hence "not crossing the bridge" :)  ?

**Comment by wcandillon** [comment]
Thank you so much, it is fixed now: https://wcandillon.github.io/react-native-redash/strings#retext
For `ReText` we use the animation value directly, no need for `setNativeProps` anymore :)
