### ISSUE TITLE
Proposal: `useImperativeGetter`

### ISSUE THREAD

**Issue by JonnyBurger** [wcandillon/react-native-redash#172]
I wanted to read an animated value on the JS thread, because I wanted to persist that value to an AsyncStorage so I could use it later.

----

I learned that I can use `call` ([thanks to your comment here](https://github.com/software-mansion/react-native-reanimated/issues/251)) to get the current value, but of course I have to wrap it in `<Animated.Code>` or `useCode` and I also have to do some extra things if I want the value 'just once'.

---

In the end I made this masterpiece of a hook which I am very proud of:
```ts
import React, {useReducer, Reducer} from 'react';
import Animated, {useCode, cond, call} from 'react-native-reanimated';

type AddListenerAction<T> = {
	type: 'add-listener';
	resolveFn: (num: T) => void;
};

type RemoveListenerAction<T> = {
	type: 'resolve';
	value: T;
};

type State<T> = {
	inProgress: number;
	resolveFns: ((num: T) => void)[];
};

export const useImperativeGetter = <T,>(
	value: Animated.Node<T>
): (() => Promise<T>) => {
	const [s, dispatch] = useReducer<
		Reducer<State<T>, AddListenerAction<T> | RemoveListenerAction<T>>
	>(
		(state, action) => {
			switch (action.type) {
				case 'add-listener':
					return {
						inProgress: 1,
						resolveFns: [...state.resolveFns, action.resolveFn]
					};
				case 'resolve':
					return {
						inProgress: 0,
						resolveFns: []
					};
				default:
					return state;
			}
		},
		{
			inProgress: 0,
			resolveFns: []
		}
	);
	const callback = React.useCallback(
		v => {
			dispatch({
				type: 'resolve',
				value: v[0]
			});
			for (const fn of s.resolveFns) {
				fn(v[0]);
			}
		},
		[s.resolveFns]
	);
	useCode(() => cond(s.inProgress, call([value], callback)), [
		s.inProgress,
		value
	]);

	return () =>
		new Promise<T>(resolve => {
			dispatch({
				type: 'add-listener',
				resolveFn: resolve
			});
		});
};
```

This is how it's used:

```ts
const value = new Animated.Value(0)
const getValue = useImperativeGetter(value)
```

now anywhere in your code you can call the returned function to get the current value.

```ts
await getValue()
// => 0
```

I took special care of avoiding concurrency issues or race conditions. So for example you can call it multiple times `Promise.all([getValue(), getValue(), getValue()])` and you should get `[0, 0, 0]`. Hence why it uses `useReducer`, to batch multiple state updates at once.

Would you like to include this in your library? Is this even a smart thing to do or is there already some easier way to do it in the ecosystem? Would love to hear your opionions.

**Comment by wcandillon** [comment]
@JonnyBurger  The use case makes perfect sense:
* People who come from vanilla animated really struggle with this use case.
* It's a nice utility even if you know how to send the value to the JS side.

I took a look at where I could use such function: https://github.com/wcandillon/can-it-be-done-in-react-native-private/blob/9dfe2f70397e91f3ff66d4baaacd4c2644139c9c/season3/src/CoinbasePro/Values.tsx#L60
I would expect the API to look like this:

```tsx
// [nodes, defaultVals, deps]
const [index] = useNodes([floor(divide(translateX, caliber))], [0], [caliber, candles, translateX]);
```

What do you think about this API?

**Comment by JonnyBurger** [comment]
Cool! I think this makes sense as well, though I think these are two different use cases: 1. Getting the value 'on-demand' by imperatively calling it, 2. Consistently get the value whenever it changes (or when it passes a threshold in this case).

I think we can make these two different (but similar) utilities. For my use case I don't want get the value everything it changes, because it would negate the benefit of running it on the native thread and also I don't want it rounded.

**Comment by wcandillon** [comment]
makes sense it’s a push/pull thingy. Can you send me an example for 1.

**Comment by JonnyBurger** [comment]
Sure! So I want to do something like this, save the current value of the Animated node so I can use it later. It would go like this:

```ts
const value = useMemoOne(() => new Animated.Value(0), []);
const getValue = useImperativeGetter(value);

const save = React.useCallback(async () => {
  const currentValue = await getValue()
  await AsyncStorage.setItem('currentValue', String(currentValue));
}, [getValue])
```

Then I could just call `save()` anytime to save the value. Hope this elaborates it! Let me know if I should PR.

**Comment by wcandillon** [comment]
This is make sense, we could call it `useNodesOnce()` to work with the other function. I guess it makes sense to return a promise. What about returning undefined until the value is available?

**Comment by JonnyBurger** [comment]
Naming sounds good to me.

Is there a point in which the value is not yet available? In initialization? Lacking a bit of knowledge there tbh

**Comment by wcandillon** [comment]
yes it wouldn't available in the first render, which why you use a hook and promise together.

**Comment by JonnyBurger** [comment]
Goood point! I just tried it out,

![image](https://user-images.githubusercontent.com/1629785/73673002-35dab180-46ae-11ea-9e16-d09e32e4f84b.png)

defining it and then getting it immediately, and it correctly returns -10 the first time, which would be even better than undefined. Is this the scenario you meant?

**Comment by doylemark** [comment]
was this ever implemented? 😀

**Comment by JonnyBurger** [comment]
With Reanimated 2 coming out we probably need another solution in the long term.

But I still use this function and it worked well, so I would recommend you to just copy the function into your codebase.

**Comment by doylemark** [comment]
Cool, thanks Jonny :)

**Comment by JonnyBurger** [comment]
So I don't need it needs to be included anymore :) Anyone can feel free to copy my function.
Closing this
