### ISSUE TITLE
Why was `preserveOffset` removed?

### ISSUE THREAD

**Issue by bartzy** [wcandillon/react-native-redash#173]
Couldn't find any issues or commits regarding its removal. Was it replaced by something else?

Thanks!

**Comment by bartzy** [comment]
Closing this as I found it was just renamed to `preserveMultiplicativeOffset`.

**Comment by dsznajder** [comment]
@bartzy no, it was renamed to `witOffset`. `preserveMultplicativeOffset` is for scaling :)

**Comment by bartzy** [comment]
Ah, thanks!
