### ISSUE TITLE
animatedValueX not being updated for Interactable

### ISSUE THREAD

**Issue by CatapultJesse** [wcandillon/react-native-redash#18]
First off just want to say I love the react-native videos. Great work.

Testing out this library and trying use the animatedValueX to run an interpolation.

Basic setup is:
```
constructor(props) {
        super(props);

        this.x = new Animated.Value(0);
        this.x.addListener(console.log);
}
```

Then in render:
```
<Interactable
                                    ref={this.cursor}
                                    snapPoints={this.state.snapPoints}
                                    onSnap={this.onSnap}
                                    horizontalOnly
                                    style={{ width: 40 }}
                                    animatedValueX={this.x}
                                    initialPosition={{ x: initialX, y: 0 }}
                                >
{...}
</Interactable>
```

The display, interaction, snapoints, onSnap, initialPosition all work fine, but for some reason the animatedValueX dosn't get updated. Neither the listener, not an interpolation I have running off it seem to work

Having a quick look through the code it looks like it should be firing off fine, also tried on animatedValueY without success.

Any ideas?

**Comment by wcandillon** [comment]
Thank you @CatapultJesse :)

`addListener` is supposed to work with reanimated now? I'm using the version shipped with the latest expo version and it doesn't seem to work there. 

It is weird that the interpolation doesn't work. Can you provide me a snack of the example and I will look into it.

**Comment by JKCooper2** [comment]
Apologies, didn't realise it was meant to be use with reanimated Animated instead of the default. Will close for now and report back if there's any issues

**Comment by wcandillon** [comment]
Haha closing for now but feel free to reopen.
