### ISSUE TITLE
Not able to drag using onGestureEvent

### ISSUE THREAD

**Issue by JBaczuk** [wcandillon/react-native-redash#181]
Here is a minimal reproducible example, lmk if there are any details I'm leaving out. I was trying to recreate the pan gesture example from the course. I'm using the iOS simulator, but I click on the box, drag, and nothing happens. I'm able to log `thePanGestureHandler` events (`onGestureEvent` and `onHandlerStateChange`) and see that it is detecting the pan gesture, but the box doesn't move. When I use [the example](https://github.com/software-mansion/react-native-gesture-handler/blob/4036fba2fbc7e05d1fea340676a2975594936e8c/Example/draggable/index.js) from `react-native-gesture-handler`, it works. I think it might be something to do with the `onGestureEvent` helper function, but I'm new to the Animated and gesture libraries, and I realize the two examples use different Animated libraries.

package.json
```
...

    "react": "~16.12.0",
    "react-dom": "~16.12.0",
    "react-native": "~0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-redash": "^9.6.0",
...
```

repro
```
import React from 'react'
import { StyleSheet, View } from 'react-native'
import Animated, { Value } from 'react-native-reanimated'

import {
  PanGestureHandler,
  State
} from 'react-native-gesture-handler'
import { onGestureEvent } from 'react-native-redash'

function Draggable (props) {
  const state = new Value(State.UNDETERMINED)
  const translationX = new Value(0)
  const translationY = new Value(0)

  const gestureHandler = onGestureEvent({
    state,
    translationX,
    translationY
  })

  const translateX = translationX
  const translateY = translationY

  return (
    <PanGestureHandler
      {...gestureHandler}
    >
      <Animated.View
        style={{
          backgroundColor: 'blue',
          height: 100,
          width: 100,
          transform: [
            { translateX },
            { translateY }
          ]
        }}
      />
    </PanGestureHandler>
  )
}

export default Draggable
```

**Comment by wcandillon** [comment]
I just copy/pasted the example in snack and it worked out of the box ( had to change the import of Value) because it is not supported yet by this version of expo.

`const {Value} = Animated;
`

If you have issues withing your app, it's probably because you might have more than one render and the identity of the animation values has changed.

**Comment by JBaczuk** [comment]
@wcandillon thanks for the quick response! That is actually good news, so I'm theoretically doing it right. I am running this in a [storybook](https://storybook.js.org/docs/guides/guide-react-native/) app so I'm not sure about re-rendering. I used the `useValues()` helper function and that appears to work! Thanks for your help, here is the fix:

```
import { onGestureEvent, useValues } from 'react-native-redash'
...
const [state, translationX, translationY] = useValues([State.UNDETERMINED, 0, 0], [])
```

**Comment by wcandillon** [comment]
great, I would also memoize the call to onGestureEvent if possible.

**Comment by JBaczuk** [comment]
Would it make sense to build that memoization into the `onGestureEvent` function, then? I'm using it like you described:

```
<PanGestureHandler
      {...gestureHandler}
    >
```

**Comment by wcandillon** [comment]
100%, we need to offer something in that direction.

**Comment by RobertFOConnor** [comment]
Thanks @JBaczuk Ran into the same issue following the course. Nothing worse than having exactly what is shown in the video and it not working. I had to modify the fix slightly to exclude the array.
`const [state, translationX, translationY] = useValues(State.UNDETERMINED, 0, 0);`
