### ISSUE TITLE
Unhandled JS Exception: undefined is not a function (near '...proc...')

### ISSUE THREAD

**Issue by german970814** [wcandillon/react-native-redash#182]
<img width="431" alt="Screen Shot 2020-03-03 at 9 20 54 PM" src="https://user-images.githubusercontent.com/15973868/75838780-dfd45900-5d94-11ea-9784-b82e14c77ea5.png">

I'm having this issue then to execute `yarn add react-native-redash`.

This is the installed dependence:

```
"react": "16.8.3",
"react-native": "0.59.4",
"react-native-redash": "^9.6.0",
```

I'm not using Expo

**Comment by wcandillon** [comment]
Did you install reanimated and gesture handler as well? At which version number?

**Comment by german970814** [comment]
I'm working with this versions of those packages:

```
"react-native-reanimated": "1.2.0",
"react-native-gesture-handler": "kmagiera/react-native-gesture-handler#ff74e0e"
```

**Comment by wcandillon** [comment]
If you upgrade reanimated to at least 1.4.0, it should work fine.

**Comment by german970814** [comment]
Great! this solves my issue. You should update the install conditions dependences in the docs
