### ISSUE TITLE
useTimingTransition is the same as useTransition

### ISSUE THREAD

**Issue by MartinGrue** [wcandillon/react-native-redash#193]
https://github.com/wcandillon/react-native-redash/blob/1e1aac72f6ea74939d93142d6b940bd9eb2e3f85/packages/core/src/Transitions.ts#L127

Why is there useTimingTransition when it's 100% the same as useTransition?

Do i miss something?

**Comment by wcandillon** [comment]
You're right, it might silly, I can remove useTimingTransition

**Comment by wcandillon** [comment]
I'm closing this for now since we reference these functions a lot in the documentation: https://wcandillon.github.io/react-native-redash/transitions. But I agree, it's more confusing than anything.
