### ISSUE TITLE
Vector problem after upgrade

### ISSUE THREAD

**Issue by sebinq** [wcandillon/react-native-redash#201]
Hello @wcandillon.

I keep getting following issue after recent 11.0.0 update.

```
src/components/PinchGesture/usePinch.tsx:70:27 - error TS2693: 'Vector' only refers to a type, but is being used as a value here.

70             Vector.invert(Vector.sub(origin, adjustedFocal)),
```

and in code:

<img width="447" alt="Screenshot 2020-04-05 at 19 19 05" src="https://user-images.githubusercontent.com/33039909/78505228-54bef800-7772-11ea-9c44-856960585373.png">

Thanks.

**Comment by wcandillon** [comment]
@sebinq sorry about that. it's called `vec` now. How come your error messages look so beautiful?

**Comment by sebinq** [comment]
It is a new LogBox by Rick Hanlon featured in 0.62 😅 Thank you so much!
