### ISSUE TITLE
[types] incorrect types for animation runners

### ISSUE THREAD

**Issue by alexichristakis** [wcandillon/react-native-redash#204]
Love this library, thank you so much for making reanimated and gesture handlers easy!

I have a small type bug with animation runners where `spring` is typed to return `Animated.Node<string | number | boolean>` which throws type errors when it's assigned to an animated value of type 'number'

This forces me to cast the node as a number with: `set(top, spring({ to: y, from: top, config }) as Animated.Node<number>)`

**Comment by wcandillon** [comment]
Thank you @alexichristakis. I suggested a fix for this at https://github.com/software-mansion/react-native-reanimated/pull/712. I'm looking to publish a fix for it in redash as well right now.

**Comment by alexichristakis** [comment]
amazing! thank you
