### ISSUE TITLE
Reanimated 1.8.0 breaks interpolatepath for android

### ISSUE THREAD

**Issue by owinter86** [wcandillon/react-native-redash#206]
I have noticed that the latest reanimated version and this commit in particular 

https://github.com/software-mansion/react-native-reanimated/commit/8a33e0e8569af03a5327d8c2ee08892aa3a1bcc2#diff-f137785d3392ec955cdfa51cd322cb53

will break the interpolatePath function in redash, so animated svg paths are no longer possible when combining redash and reanimated 1.8.0. 

I can confirm that reverting this commit in 1.8.0 fixes the issue.

**Comment by owinter86** [comment]
cross post 
https://github.com/software-mansion/react-native-reanimated/issues/718

**Comment by wcandillon** [comment]
@owinter86 thank you for looking into it. Can you reproduce the bug with a simple string animation value (no redash involved). Is there a way I could switch the formatting of the path in redash so that it would work with 1.8.0?

**Comment by owinter86** [comment]
@wcandillon string animations are fine as long as they are not used in the path animation of an SVG, i think it all breaks down when the point in the path goes from an integer to a decimal point, I believe you would have to change the way redash detects integer values and append `.0` to the string. But I am afraid this may not be the nicest solution.

**Comment by wcandillon** [comment]
Can you provide me some small examples? With no redash involved?

**Comment by owinter86** [comment]
This is using the Retext import from redash but is just the TextInput hack you created, this works fine on android as a basic string aniamtion.
```
import React from 'react';
import Animated, { concat, Easing } from 'react-native-reanimated';
import { ReText } from 'react-native-redash';
import { View } from 'react-native';

export default function App() {
  const animValue = React.useRef(new Animated.Value(1));

  React.useEffect(() => {

    Animated.timing(animValue.current, {
      toValue: 2,
      duration: 1000,
      easing: Easing.linear,
    }).start();
  }, []);

  return (
    <View style={{ marginTop: 40 }}>
      <ReText text={concat(animValue.current)} style={{ fontSize: 50 }} />
    </View>
  );
}
```

**Comment by owinter86** [comment]
I believe it is unrelated to the redash implementation and this is a basic example of it not working without the interpolatePath method from redash.
```
import React from 'react';
import Animated, { concat, Easing } from 'react-native-reanimated';
import { View } from 'react-native';
import Svg, { Path } from 'react-native-svg';

const AnimatedPath = Animated.createAnimatedComponent(Path);

export default function App() {
  const animValue = React.useRef(new Animated.Value(1));

  React.useEffect(() => {
    Animated.timing(animValue.current, {
      toValue: 200,
      duration: 1000,
      easing: Easing.linear,
    }).start();
  }, []);

  return (
    <View style={{ marginTop: 40 }}>
      <Svg height="100" width="100">
        <Path d="M0.0,0.0 C0.0,0.0 200.0,0.0 200.0,0.0" fill="none" stroke="red" strokeWidth="5" />
      </Svg>

      <Svg height="100" width="400">
        <AnimatedPath
          d={concat('M', concat(animValue.current), '0.0 C0.0,0.0 200.0,0.0 200.0,0.0')}
          fill="red"
          stroke="red"
          strokeWidth="5"
        />
      </Svg>
    </View>
  );
}```

**Comment by owinter86** [comment]
Fixed in reanimated
