### ISSUE TITLE
Timing with delay not animated

### ISSUE THREAD

**Issue by VictorAtPL** [wcandillon/react-native-redash#212]
I am using following code to animate an element:
```javascript
<Animated.Code>
    {() =>
        block([
            set(this.animatedHeightValue, 30),
            set(this.animatedHide, 0),
            delay(set(this.animatedHide, 1), 3000),
            cond(
                and(
                    eq(this.animatedHide, 1),
                    neq(this.animatedHeightValue, 0)
                ),
                [
                    set(
                        this.animatedHeightValue,
                        timing({
                            clock: this.clock,
                            easing: Easing.back(),
                            from: this
                                .animatedHeightValue,
                            to: 0.0,
                            duration: 1500,
                        })
                    ),
                ]
            ),
        ])
    }
</Animated.Code>
```

If I remove `delay`, the animation works smooth. However, if I keep it, it looks like the animation is done during the delay period, so when the delay ends, the element just disappears.

I found `react-native-reanimated` and `react-native-redash` docs very unclear and there is no many examples. I guess watching the YouTube videos could help me solving this problem, but I think leaving an answer here in Issues could be beneficial for the library future users.

**Comment by nathvarun** [comment]
Any luck with this ?

**Comment by VictorAtPL** [comment]
Yes.

Here is the code: https://gist.github.com/VictorAtPL/362adb6dfcb1ca825d423e8b24bb5014
I publish it on MIT license.

The code is quasi-optimal I think. I didn't know how to implement it better.

@wcandillon 
Also, I would like to tell, that I think what you do is not fair. You published a library, without good quality documentation and you do not help people to fix their problems in issues. In almost every YT movie you recommend to buy your course and I think you, deliberately, keep not to address the issues on Github.

It's just sad. I think you're too focused on money.

**Comment by ltcaosj** [comment]
I am with you @VictorAtPL
