### ISSUE TITLE
Android - onSnapTo throws a.tension (undefined not an object)

### ISSUE THREAD

**Issue by CatapultJesse** [wcandillon/react-native-redash#22]
I'm making a tappable slider similar to your demo, but on Android when you do a `this.cursor.current.snapTo({ index: value });` it throws an error getting the snapAnchor tension.

Snack: https://snack.expo.io/@jkcooper/android-slider

Also the call seems unreliable. On iOS it will make the call and snap (as seen by onSnap updating the state with the new value), but the slider won't move. Some of the time it works, some of the time not.

Let me know if you need any other info

**Comment by wcandillon** [comment]
Indeed and I was unsuccessful to try to fix it. My plan would be to remove this method for me. Since the implementation comes from reanimated originally, it is hard for me to maintain it.

**Comment by CatapultJesse** [comment]
I believe I've got a working behaviour by calling it via a ref and doing:

```
Animated.timing(this.cursor.current.snapAnchor.x, {
                toValue: this.state.snapPoints[value].x,
                duration: 60,
                easing: Easing.linear,
            }).start();
```

**Comment by wcandillon** [comment]
@CatapultJesse I'm glad you found a good solution for this. We stopped support for `<Interactable>` but hopefully in the future we able to provide capabilities via redash that can easily match `<Interactable>` use cases. Please let me know if you have any questions.
