### ISSUE TITLE
TypeError for Android

### ISSUE THREAD

**Issue by MauroTaliente** [wcandillon/react-native-redash#221]
### Hello,

I have an error in Android when I want to use the library it gives me a Type error:

![Screenshot_20200416-043113_Expo](https://user-images.githubusercontent.com/10060947/79510778-65922800-8014-11ea-870d-2a49992d4805.jpg)

my package:
```javascript
{
    “react-native”: “https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz”,
    “react-native-gesture-handler”: “~1.5.0",
    “react-native-reanimated”: “~1.4.0",
    “react-native-redash”: “^12.1.5",
}
```

Note: I think that error was fixed a while ago as I searched but I don't know why I have it,
Going back to version 5.0 I can work perfectly.

I am at your disposal to help.
Regards.

**Comment by wcandillon** [comment]
Can you upgrade the version of reanimated you are using (SDK 37)? I'm working on a fix for this as well.
