### ISSUE TITLE
Error in Android for version 12.1.0 and expo sdk 36

### ISSUE THREAD

**Issue by spyr0s** [wcandillon/react-native-redash#230]
I got this error in android 
12.0.4 was OK
![Screenshot_2020-04-20-10-26-23-456_host exp exponent](https://user-images.githubusercontent.com/1019278/79725299-b003f500-82f1-11ea-9a56-4cda343f294a.jpg)

I use EXPO v36 (so reanimated version 1.4.0 , maybe that's the issue?)

**Comment by wcandillon** [comment]
That's definitely the issue, I could make the change, however, I'm afraid that with 1.4.0 there are other things that break with 🤔Would you like me to fix the issue anyways? I'd be happy to.

**Comment by spyr0s** [comment]
HI,
I upgraded EXPO to SDK 37 (reanimated v1.7.0) and it seems to work now.
No need to dix, just  leave this issue here just for others  who may have the same problem

**Comment by codervss** [comment]
"react-native": "0.61.4",
"react-native-reanimated": "^1.8.0",
"react-native-redash": "^12.6.0",

I do not use Expo and i am still getting this error.
Please help me @wcandillon
