### ISSUE TITLE
Is bInterpolate deprecated?

### ISSUE THREAD

**Issue by nandorojo** [wcandillon/react-native-redash#253]
I don't see it on the docs, and it doesn't seem to be exported. Is it no longer available?

<img width="650" alt="Screen Shot 2020-04-30 at 2 28 00 PM" src="https://user-images.githubusercontent.com/13172299/80745773-ccbcdb80-8aee-11ea-89f8-f6c1f06f1250.png">

**Comment by wcandillon** [comment]
it's named `mix()` now. Sorry about that.

**Comment by nandorojo** [comment]
Got it, no worries! It could be useful to have that somewhere on the docs (or maybe a warning in the function), but no big deal. Thanks for the quick reply.

**Comment by dropcmd** [comment]
@wcandillon Glad I found this, thanks. Perhaps update or add a note in the description of your React Native Accordion List video.
