### ISSUE TITLE
Vec.invert is undefined

### ISSUE THREAD

**Issue by MadeinFrance** [wcandillon/react-native-redash#265]
Hi W,

Just reporting that from v`12.5.6` to `13.0.0`, `Vec.invert` is undefined.

This is my snippet:

```
    const state = new Value(State.UNDETERMINED)
    const origin = vec.createValue(0, 0)

    const adjustedFocal = vec.add(
      {
        x: -SIZE / 2,
        y: -SIZE / 2,
      },
      focal
    )

...

cond(
 eq(state, State.ACTIVE),
 vec.set(pinch, vec.invert(vec.sub(origin, adjustedFocal)))
),
...
```

Can anyone help me to migrate `vec.invert`?

**Comment by shawnmitchell** [comment]
I think it's been replaced with vec.minus

**Comment by MadeinFrance** [comment]
`vec.minus` solved my issue.

Seems like the [documentation](https://wcandillon.github.io/react-native-redash/vectors#vec) is not updated.
