### ISSUE TITLE
Error: outputRange cannot include undefined, from useValues

### ISSUE THREAD

**Issue by sumanthyedoti** [wcandillon/react-native-redash#278]
The code is giving error after using `useValues`
```
const [show, setShow] = useState(true);
const clock = useClock([]);
const startAnimation = new Value(1);
const [startTime, from, to] = useValues([0, 0, 0], []);
const endTime = add(startTime, duration);
const opacity = interpolate(clock, {
  inputRange: [startTime, endTime],
  outputRange: [from, to],
  extrapolate: Extrapolate.CLAMP,
});
```

Error: `Invariant Violation: outputRange cannot be undefined`

**Comment by sumanthyedoti** [comment]
This is happening with latest release. Worked fine after downgrading to `12.5.3`

**Comment by CptFabulouso** [comment]
It's not changed in docs, but v14 change implementation. See here https://github.com/wcandillon/react-native-redash/releases/tag/v14.0.0
So you should have `const [startTime, from, to] = useValues(0, 0, 0);`
From what I see in docs the `useValues` didn't accept second parametr even before.

**Comment by CptFabulouso** [comment]
Also now considering the docs are correct, the `useClock` doesn't accept any parameters https://wcandillon.github.io/react-native-redash/hooks#useclocks 
I think none of these hooks accept dependency arrays

**Comment by francosta** [comment]
@CptFabulouso I think you are right for the docs on `useClock`. However, the docs on `useValues` still expect an array, which is wrong. After looking at your link on the implementation changes for v14, I changed it to just values outside of an array and it is now working. Thank you.

**Comment by philipbulley** [comment]
I've just come across this too, reproduced here: https://snack.expo.io/@pbcodes/insane-scones

Changing the `useValues([0, 0, 0, 0])` to `useValues(0, 0, 0, 0)` works. As @francosta said, the docs are out of date.

**Comment by wcandillon** [comment]
Sorry for the confusion and thank you for reporting it, publishing a new version of the docs now.
