### ISSUE TITLE
withTransition when used inside a functional component repeats on rerender ?

### ISSUE THREAD

**Issue by a-eid** [wcandillon/react-native-redash#283]
William thank you so much for the amazing package as well as your course && and the youtube video series.

  
when I use the `withTransition` function lets say with a timeing transition that goes from (0 => 1), if I'm already at 0 and the component rerenders, the animation is repeated. 

in order to avoid that I confert the component to a class component and use the `withTransition` as a class property then it works great.

**Comment by zmtmaster** [comment]
Try wrapping withTransition with a useRef to keep the ref to the value and not change it on re-render of the component.

Something like:
```
const open = useValue(0);
const transition = useRef(withTransition(open)).current;
```

Does that help preventing the re-render?

**Comment by noahsemus** [comment]
Was also having this problem and using the useRef fixed it for me. Many thanks!
