### ISSUE TITLE
snapTo not always working

### ISSUE THREAD

**Issue by chrise86** [wcandillon/react-native-redash#29]
Using the following:
```
<Interactable
  ref={panel => this.panel = panel}
  verticalOnly={true}
  snapPoints={SNAP_POINTS}
  boundaries={{ top: -300 }}
  initialPosition={{ x: 0, y: Screen.height + 250 }}
  animatedValueY={this._deltaY}
>
  <TouchableHighlight onPress={this.openPlayer}>
 // truncated
```
Where `openPlayer` is:
```
private openPlayer = (): void => {
  if (this.panel) {
    this.panel.snapTo({ index: SNAP_POINTS.indexOf(OPEN_POSITION) })
  }
}
```
When I press the button to trigger the snap, it seems to only work intermittently. It registers the press, and I can see by logging that the panel ref exists, but sometimes the snap just doesn't happen.

**Comment by wcandillon** [comment]
Sorry for the confusion, we don't support this method, unfortunately.

**Comment by chrise86** [comment]
Oh, what about https://github.com/wcandillon/react-native-redash/blob/master/src/Interactable.tsx#L577?

**Comment by wcandillon** [comment]
Sorry about that, I'm commenting this method out for now. Unfortunately, if you want to imperatively control your animation values, you'll have to either build your own custom component or use some offset value in combination with `animatedValueX` and `animatedValueY`.

**Comment by chrise86** [comment]
Like this?
```
Animated.timing(this._deltaY, {
  duration: 500,
  toValue: OPEN_Y,
  easing: Easing.inOut(Easing.ease),
}).start()
```
Doesn't seem to alter anything :-/

**Comment by wcandillon** [comment]
I meant via `<Interactable {...{animatedValueX, animatedValueY}}  />` and then snapping on a third value (`offsetX` for instance) and then have `x = add(animatedValueX, offsetX)`. I don't have any confidence this would work, just wanted to throw an idea out there 😅 

We stopped support for `<Interactable>` but hopefully in the future we able to provide capabilities via redash that can easily match `<Interactable>` use cases. Please let me know if you have any questions.
