### ISSUE TITLE
Animated.ScrollView onScroll Error

### ISSUE THREAD

**Issue by MartinSchnit** [wcandillon/react-native-redash#302]
Hi all,

I have a problem implementing onScrollEvent on an animated ScrollView

```
import { useValue, onScrollEvent, interpolateColor } from 'react-native-redash';

const x = useValue(0);
const onScroll = onScrollEvent({ x });

<Animated.ScrollView 
                    horizontal 
                    snapToInterval={width} 
                    decelerationRate="fast" 
                    showsHorizontalScrollIndicator={false} 
                    bounces={false}
                    scrollEventThrottle={1}
                    {...{onScroll}}
                >

</Animated.ScrollView>
```

When i try to scroll I have this error message : 
**`this.props.onScroll is not a function. (In 'this.props.onScroll(e), this.props.onScroll' is an instance of AnimatedEvent)`**

Thanks for your time <3

**Comment by wcandillon** [comment]
Sorry about that. It looks like this now:

```
  const { scrollHandler, x, y } = useScrollHandler();
//...
          {...scrollHandler}
```
and you don't need to add the scrollEventThrottle={1} anymore. I hope this helps.

**Comment by MartinSchnit** [comment]
thanks for you time and your work William

**Comment by kaisertuan98** [comment]
const Onboarding = () => {
  //const x = useValue(0);
  const { scrollHandler, x, y } = useScrollHandler();
  const backgroundColor = interpolateColor(x, {
    inputRange: [0, width, width * 2, width * 3],
    outputRange: ["#BFEAF5", "#BEECC4", "#FFE4D9", "#FFDDDD"],

  });
  return (
    <View style={styles.container}>
      <Animated.View style={[styles.slider, { backgroundColor }]}>
        <Animated.ScrollView
          horizontal
          snapToInterval={width}
          decelerationRate="fast"
          showsHorizontalScrollIndicator={false}
          bounces={false}
          {...scrollHandler}
        >
          <Slide label="iPhone" />
          <Slide label="Watch" right />
          <Slide label="iPad" />
          <Slide label="AirPods" right />
        </Animated.ScrollView>
      </Animated.View>
      <View style={styles.footer}>
        <Animated.View
          style={{ ...StyleSheet.absoluteFillObject, backgroundColor }}
        />
I can't do as instructed, my background is still white, please help me, thank you everyone
