### ISSUE TITLE
Animated.ScrollView onScroll Error

### ISSUE THREAD

**Issue by emtesenair** [wcandillon/react-native-redash#305]
I am having an issue with `useScrollHandler()`

```
import { interpolateColor, useScrollHandler } from "react-native-redash";

const { scrollHandler, x } = useScrollHandler();

<Animated.ScrollView
    horizontal
    snapToInterval={width}
    decelerationRate="fast"
    showsHorizontalScrollIndicator={false}
    bounces={false}
    {...scrollHandler}
>
...
</Animated.ScrollView>
```
When I try to scroll this error message is presented:
`this.props.onScroll is not a function. (In 'this.props.onScroll(e), this.props.onScroll' is an instance of AnimatedEvent)`

**Package versions**
    "expo": "~38.0.8",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-reanimated": "~1.9.0",
    "react-native-redash": "^14.2.2"

**Comment by emtesenair** [comment]
Found the issue. 

I was `Animated` from react-native instead of from react-native-reanimated

**Comment by Bensigo** [comment]
> Found the issue.
> 
> I was `Animated` from react-native instead of from react-native-reanimated

Nice. please can you close this issue
