### ISSUE TITLE
Animated.View is giving error from redash

### ISSUE THREAD

**Issue by pavan-kumar-murapala** [wcandillon/react-native-redash#308]
Using Expo cli

package json:

	"dependencies": {
		"@react-native-community/masked-view": "0.1.10",
		"@react-navigation/native": "^5.7.0",
		"@react-navigation/stack": "^5.7.0",
		"@use-expo/font": "^2.0.0",
		"expo": "~38.0.8",
		"expo-status-bar": "^1.0.2",
		"react": "~16.11.0",
		"react-dom": "~16.11.0",
		"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
		"react-native-gesture-handler": "~1.6.0",
		"react-native-reanimated": "^1.9.0",
		"react-native-redash": "^14.2.2",
		"react-native-safe-area-context": "~3.0.7",
		"react-native-screens": "~2.9.0",
		"react-native-web": "~0.11.7"
	},
	"devDependencies": {
		"@babel/core": "^7.8.6",
		"babel-preset-expo": "~8.1.0"
	},

typeError: undefined is not an object (evaluting '_reactNativeRedsh.Animated.View'

	<Animated.View style={[styles.slides, { bgColor }]} >
			<Animated.ScrollView
				horizontal
				snapToInterval={width}
				bounces={false}
				showsHorizontalScrollIndicator={false}
				decelerationRate={"fast"}
				scrollEventThrottle={1}
				{...{ onScroll }}
			>

![Screenshot_20200717_145938](https://user-images.githubusercontent.com/4281312/87771956-b2b5ae00-c83e-11ea-98cc-8b8652f2f0d4.jpg)

**Comment by RobertPechaCZ** [comment]
Do you have this?
```
import Animated from "react-native-reanimated";
const { View } = Animated;
```

**Comment by pavan-kumar-murapala** [comment]
Yes it is working with above syntax.
