### ISSUE TITLE
WithSpringTransition lagging since Version 14.2.4

### ISSUE THREAD

**Issue by alexco2** [wcandillon/react-native-redash#324]
Hello William,
the withSpringTransition, implemented like here : https://www.youtube.com/watch?v=hh7vfMzHTIg&t=1433s (i´m a big fan btw :D) is with version 14.2.4 increadibly laggy/ broken. Version 14.2.3 works perfect though. Is this intentional/ do I need to adapt the code, or is there a bug? 
Thank you so much for your great work!
Br, Alex

**Comment by wcandillon** [comment]
I apologize for this regression 😐
I'm struggling to stop the regression, do you have the same issue with withTimingTransition?

**Comment by alexco2** [comment]
Don´t worry, version 14.2.3 works perfactly fine and i´ll use that ;)
WithTimingTransition (14.2.4) seems to be a lot more smooth in comparison to WithTimingTransition (14.2.4). In Version 14.2.3 though both, WithTimingTransition and WithSpringTransition, are way more smooth. It´s a big difference.

**Comment by wcandillon** [comment]
Is there a way you could recommend me to experience this new slowness?

**Comment by alexco2** [comment]
I basically took the same code you used in https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season3/src/Chrome but without the x coordinate. I could create a snack but I´ve never done that before, so that might take some time :D You probably could just try it with your code :)

**Comment by JonnyBurger** [comment]
Also experienced a change in behavior of `withSpringTransition` in v14.2.4.

Here is an example component:
https://github.com/JonnyBurger/touchable-scale/blob/master/src/index.tsx

I copied the `withSpringTransition` function from 14.2.1 into my project, but if I import the function from 14.2.4, there is no spring at all.

**Comment by alexco2** [comment]
Does anybody know if this is resolved with version 15.?
