### ISSUE TITLE
Upgraded to redash 15, v1 not found

### ISSUE THREAD

**Issue by beetlebum** [wcandillon/react-native-redash#331]
I just upgraded to Redash 15.0.0 and following the documentation, I changed my imports to
```import { onScrollEvent, useValues } from 'react-native-redash/v1';```
but I'm getting build errors ``` Unable to resolve module `react-native-redash/v1```, what am I doing wrong?
Is v1 a separate package now?

Thanks

**Comment by wcandillon** [comment]
My apologies about that, I'm working on a fix right now, check back in a couple of hours

**Comment by beetlebum** [comment]
@wcandillon thanks William

**Comment by wcandillon** [comment]
I tried the `v15.0.1` (and updated the migration instructions as well) and it worked well for me, let me know if this works for you too.

**Comment by beetlebum** [comment]
![image](https://user-images.githubusercontent.com/227258/92479981-2c816c80-f1dc-11ea-8195-933b33121a48.png)
I'm still getting this issue

**Comment by wcandillon** [comment]
This is fixed in v15.0.2 ;-) Didn't realize that you were using v2.

**Comment by wcandillon** [comment]
sorry for the mess, I went a bit too quick, I did manage to make the package still compatible with v1 even tough v2 break compatibility with v1 (interpolate -> interpolateNode, Easing -> EasingNode)
