### ISSUE TITLE
Not able to use interpolateColor

### ISSUE THREAD

**Issue by rawatnaresh** [wcandillon/react-native-redash#346]
As per the documentation [here](https://wcandillon.gitbook.io/redash/colors#interpolatecolor), my interpolationColor funtion looks like this
```
  const x = new Value(0);

  const backgroundColor = useDerivedValue(() => {
    return interpolateColor(
      x, // ERROR: Argument of type 'Value<0>' is not assignable to parameter of type 'number'
      [0, width, width * 2, width * 3],
      ['#BFEAF5', '#BEECC4', '#FFE4D9', '#FFDDDD']
    );
  });
```
Also, when I'm adding the `backgroundColor` to the styles I'm getting the following error

```
 <Animated.View style={[styles.slider, backgroundColor]}> // Error at this line
        <Animated.ScrollView
          horizontal
          snapToInterval={width}
          decelerationRate="fast"
          showsHorizontalScrollIndicator={false}
          bounces={false}
          {...onScroll}>
          <Slide label="Relaxed" />
          <Slide label="Playfull" right />
          <Slide label="Excentric" />
          <Slide label="Funky" right />
        </Animated.ScrollView>
  </Animated.View>
```

```
Type 'SharedValue<string | number>' is not assignable to type 'false | AnimateStyle<ViewStyle> | RegisteredStyle<AnimateStyle<ViewStyle>> | RecursiveArray<false | AnimateStyle<ViewStyle> | RegisteredStyle<...>> | readonly (false | ... 1 more ... | RegisteredStyle<...>)[]'.
```
I'm using 
- "react-native-reanimated": "^2.0.0-alpha.6",
- "react-native-redash": "^15.1.4",

**Comment by wcandillon** [comment]
you need to use useAnimatedStyle to return the style.

**Comment by wcandillon** [comment]
closing this one for now. feel free to reopen if needed.

**Comment by rawatnaresh** [comment]
@wcandillon updated code using `useAnimatedStyle` but the background color is still not getting updated because the `interpolateColor` is returning integer instead of a color. so I had to manually change the integer to the color value to make it work.

```
  const backgroundStyles = useAnimatedStyle(() => {
    const backgroundColor = interpolateColor(
      scrollOffset.value,
      [0, width, width * 2, width * 3],
      ['#BFEAF5', '#BEECC4', '#FFE4D9', '#FFDDDD']
    );
    const color = '#' + (backgroundColor & 0x00ffffff).toString(16).padStart(6, '0');
    return {backgroundColor: color};
  });
```

is this the expected behavior?

**Comment by Stevemoretz** [comment]
> @wcandillon updated code using `useAnimatedStyle` but the background color is still not getting updated because the `interpolateColor` is returning integer instead of a color. so I had to manually change the integer to the color value to make it work.
> 
> ```
>   const backgroundStyles = useAnimatedStyle(() => {
>     const backgroundColor = interpolateColor(
>       scrollOffset.value,
>       [0, width, width * 2, width * 3],
>       ['#BFEAF5', '#BEECC4', '#FFE4D9', '#FFDDDD']
>     );
>     const color = '#' + (backgroundColor & 0x00ffffff).toString(16).padStart(6, '0');
>     return {backgroundColor: color};
>   });
> ```
> 
> is this the expected behavior?

Yes that happens to me too, in some cases you can directly use that integer as a color.

But in other cases you end up converting it to an rgba or a hex.
