### ISSUE TITLE
tsconfig.json

### ISSUE THREAD

**Issue by sabriyasar** [wcandillon/react-native-redash#348]
react-native-redash version 14.3.2 installed. There is an error in tsconfig.json. The tscofing.json I use is like the link below.

https://gist.github.com/wcandillon/97e5995b39dd079b7727002500ac5f88

Issue: http://prnt.sc/ulkvw0

**Comment by wcandillon** [comment]
This config is only for v15. (with the v1 types include).

**Comment by sabriyasar** [comment]
> (with the v1 types include).

What are the tsconfig.json codes I should use?

**Comment by wcandillon** [comment]
The same but without the include

**Comment by sabriyasar** [comment]
> The same but without the include

Thank you.

**Comment by wcandillon** [comment]
closing it, feel free to reopen if needed.
