### ISSUE TITLE
Math.ts functions 'lerp' and 'mix' are equivalent

### ISSUE THREAD

**Issue by gregzanch** [wcandillon/react-native-redash#384]
In [src/Math.ts](https://github.com/wcandillon/react-native-redash/blob/5abc433ac2f583e272972985e38726ddfc0c0030/src/Math.ts#L19), the [lerp](https://github.com/wcandillon/react-native-redash/blob/5abc433ac2f583e272972985e38726ddfc0c0030/src/Math.ts#L19) function is the same function as [mix](https://github.com/wcandillon/react-native-redash/blob/5abc433ac2f583e272972985e38726ddfc0c0030/src/Math.ts#L14).

**Comment by wcandillon** [comment]
Thanks for catching this 🙌🏻
