### ISSUE TITLE
withTiming() callback not getting triggered when using withPause()

### ISSUE THREAD

**Issue by sbattou** [wcandillon/react-native-redash#390]
I have the following code snippet where the animation and pausing work fine. 

`some.value = withPause(
      withTiming(1, { duration }, (isFinished) => {
        console.log(123);
      }),
      isPaused,
   );`

The callback does not seem to get triggered when the animation is finished when using the withPause function. I tried annotating the callback function as a "worklet" but still no luck. Any idea on why this isn't working?

**Comment by wcandillon** [comment]
Could it be because you are using alpha8? It looks like these APIs have changed and redash should be updated in that regard.

**Comment by sbattou** [comment]
Hi @wcandillon, thank you for getting back to me. I'm actually using reanimated alpha 6 and the latest redash (v15.11.1). Do you know what version introduced this issue?

**Comment by wcandillon** [comment]
it should work with alpha6

**Comment by sbattou** [comment]
Sorry, I got busy with some other stuff but I'm still having the same issue. Have you had the chance to test it on your end?

**Comment by wcandillon** [comment]
Thanks for reporting this, could you check if https://github.com/wcandillon/react-native-redash/pull/409 solves the issue?

**Comment by sbattou** [comment]
Just did a quick test and it seems to be working. Thanks @wcandillon
