### ISSUE TITLE
reanimated workletInit is not a function

### ISSUE THREAD

**Issue by LoganxDev** [wcandillon/react-native-redash#395]
Trying to follow along with the gestures tutorial to create a draggable view and I get the following error when trying to use the `usePanGestureHandler` hook.

`TypeError: global.__reanimatedWorkletInit is not a function. (In 'global.__reanimatedWorkletInit(_f)', 'global.__reanimatedWorkletInit' is undefined)`

I see there's an issue in reanimated related to this, do I need to downgrade?

Package versions are:
```
"react-native-reanimated": "^2.0.0-alpha.9.1",
"react-native-redash": "^15.11.1"
```

**Comment by wcandillon** [comment]
@LoganxDev sorry that you experienced this. The issue and workaround is described here https://github.com/software-mansion/react-native-reanimated/issues/1423

**Comment by LoganxDev** [comment]
Ah okay that got me past the error, thanks!

**Comment by lcorniglione** [comment]
Hi,

I am having the exact same issue, but I cannot make that workaround work. Where I am supposed to put this function?

` global.__reanimatedWorkletInit = () => {};`

Thanks!

**Comment by wcandillon** [comment]
@lcorniglione Another workaround is to use reanimated. this will import the real init function.

**Comment by mhjey** [comment]
@wcandillon 
What do you mean with "use reanimated"? I do use reanimated 2 in my project but that does not seem to help and the workaround does not seem to work either, I wrote `global.__reanimatedWorkletInit = () => {};` on every possible file but still I keep on getting: 
```
Error: Requiring module "node_modules/react-native-redash/lib/module/Animations.js", which threw an exception: TypeError: global.__reanimatedWorkletInit is not a function. (In 'global.__reanimatedWorkletInit(_f)', 'global.__reanimatedWorkletInit' is undefined)
```

"expo": "^40.0.0",
 "react-native-reanimated": "2.0.0-rc.0",
 "react-native-redash": "^16.0.4",

**Comment by wcandillon** [comment]
I might sound silly but this happens if you don't import the "react-native-reanimated" module. Because the reanimated plugin works but doesn't have access to the reanimated runtime.

**Comment by ghmeec** [comment]
am getting the same error

**Comment by KestasVenslauskas** [comment]
Any update on this? How to actually fix this issue?

**Comment by thisisgit** [comment]
Thanks to [this post](https://dev.to/mrmurphy/animating-text-content-with-redash-and-reanimated-2-3cmg), simply adding `import 'react-native-reanimated';` on top of the file solved my issue.

**Comment by ehsan6sha** [comment]
For me putting import for react-native-reanimated before import for redash solved the issue

**Comment by Aaronhuu** [comment]
This works for me.  https://github.com/software-mansion/react-native-reanimated/issues/1380#issuecomment-865143328

**Comment by nandorojo** [comment]
This issue is happening on Web in v2.8.0.

**Comment by UchennaOkafor** [comment]
> This issue is happening on Web in v2.8.0.

Did you manage to solve it?

**Comment by nandorojo** [comment]
Yeah. Upgrade to the latest RNGH (2.4.1), the latest Reanimated, make sure you don’t have duplicate versions with `yarn why`, remove `.next` or any corresponding cache folders, and run `yarn`

**Comment by himrocks33** [comment]
@nandorojo I'm still having the same issue on web even after your suggested fix.  Any ideas?

**Comment by exzos28** [comment]
Start metro with cache reset
`yarn start --reset-cache`

This helped me solve the problem

**Comment by Gamma169** [comment]
@nandorojo and for those of you running into the problem v2.8.0 on web, I was able to resolve the issue by adding `global.__reanimatedWorkletInit = () => {};` to `/lib/reanimated2/core.js`  Note that it is the `lib` folder and not the `src` folder that made it work.

**Comment by Gamma169** [comment]
@wrsulliv, are you familiar with [patch-package](https://github.com/ds300/patch-package)?  I created a patch file to automatically add the line when I run `yarn`.  So I don't have to worry about it, and haven't thought of it since.

**Comment by wcandillon** [comment]
@Gamma169 can I see the patch? anything we could add to redash?

**Comment by wrsulliv** [comment]
Thanks @Gamma169  I ended up doing the same.  I documented is here if it helps @wcandillon : https://github.com/software-mansion/react-native-reanimated/issues/3111#issuecomment-1179370383

**Comment by wcandillon** [comment]
@wrsulliv Thank you for following up on this. With Reanimated on web, I am not experiencing the issue. Let me know if there are any changes you would like me to add to this package. By looking at the issue you linked on github it wasn't obvious what I should do.

**Comment by challme28** [comment]
> @nandorojo and for those of you running into the problem v2.8.0 on web, I was able to resolve the issue by adding `global.__reanimatedWorkletInit = () => {};` to `/lib/reanimated2/core.js` Note that it is the `lib` folder and not the `src` folder that made it work.

It worked for me. 
I think is the cleanest solution, no polyfill file or git project modified
