### ISSUE TITLE
LICENSE for this library

### ISSUE THREAD

**Issue by enahum** [wcandillon/react-native-redash#396]
Hey @wcandillon would you mind adding a license file to the repo so we can reference it at Mattermost? We have an open PR here https://github.com/mattermost/mattermost-mobile/pull/4976 add we are missing the license for your lib.

Btw: Thanks for all the work you put on this library and all your videos ;)

Bye from beautiful Santiago de Chile my Zurich colleague :P

**Comment by wcandillon** [comment]
Thks a lot! Done 👍
