### ISSUE TITLE
ReText text not changed but printed well in console

### ISSUE THREAD

**Issue by mym0404** [wcandillon/react-native-redash#399]
### Description
The `SharedValue<string>` from `useDeriviedValue` is changed well but doesn't affect `ReText` well... 

```tsx
  const percentageText = useDerivedValue(() => {
    const factor = cursorX.value / graphWidth; // 0(left end in graph) ~ 1(right end in graph)
    const dataIndex = Math.round(factor * (dataCount - 1)); // 0 | 1 | 2 | ... | n - 1

    const text = `상위 ${datas[dataIndex].toFixed(1)}%`;
    console.log(text);
    return text;
  });

...

<ReText text={percentageText} />
```

![image](https://user-images.githubusercontent.com/33388801/99893061-1190a580-2cbf-11eb-81c6-fe925fe2d9ba.png)
![1](https://user-images.githubusercontent.com/33388801/99893067-3422be80-2cbf-11eb-9691-8f3ee6f10f0f.gif)

Is there any something wrong in my code?

### Environment
```json
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-reanimated": "2.0.0-alpha.9.1",
"react-native-redash": "15.11.1",
```

**Comment by mym0404** [comment]
I couldn't solve this problem. So, I am just using `setInterval` to check `SharedValue` and update state of `useState` in JS thread side.
```ts
  useEffect(() => {
    const h = setInterval(() => {
      updatePercentageText(cursorX.value);
      updateDateText(cursorX.value);
    }, 500);

    return () => {
      clearInterval(h);
    };
  }, [cursorX.value, updatePercentageText, updateDateText]);
```

**Comment by mrbrentkelly** [comment]
I believe you need to whitelist the `text` native prop for this to work...

`Animated.addWhitelistedNativeProps({ text: true });`

Source https://github.com/software-mansion/react-native-reanimated/issues/1448#issuecomment-730482678

**Comment by mym0404** [comment]
I solve this problem with `runOnJS` and `useAnimationReaction`
```ts
  useAnimatedReaction(
    () => cursorX.value,
    (x) => {
      runOnJS(updatePercentageText)(x);
      runOnJS(updateDateText)(x);
    },
  );
```

**Comment by wcandillon** [comment]
Thank you for reporting this. You can use `Animated.addWhitelistedNativeProps({ text: true });` as a temporary fix.
Just out of curiosity, how do you update the `<Text  />` component on the JS thread without triggering a React re-render?

**Comment by mym0404** [comment]
> Thank you for reporting this. You can use `Animated.addWhitelistedNativeProps({ text: true });` as a temporary fix.
> Just out of curiosity, how do you update the `<Text />` component on the JS thread without triggering a React re-render?

@wcandillon Thank you fir fixes. In my last comment, the `updateXXX` methods are set state from `useState`. So the React re-render has been triggered.
