### ISSUE TITLE
Interactable doesn't scroll Inside a Flatlist or scrollview

### ISSUE THREAD

**Issue by maleking** [wcandillon/react-native-redash#40]
i created a SwipeableRow component with Interactable and when i add it in scrollview it doesn't scroll
its any way to priority scrollview scroll over Interactable onDrag ?

**Comment by sivakumar-cf** [comment]
+1 I am also facing the same

**Comment by wcandillon** [comment]
Unfortunatelye we stopped support for <Interactable> but hopefully in the future we able to provide capabilities via redash that can easily match <Interactable> use cases. Please let me know if you have any questions.

**Comment by maleking** [comment]
Actually I use redash because of Interactable it was funny to create complex gesture base animation with simple structure
But In my case I don't now  how to create SwipeableRow inside a Flatlist with readah and reanimated without previous problem
