### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by sabriyasar** [wcandillon/react-native-redash#400]
I am using React Native Typescript. I want to use Hook. When I write the code in the 1st image, I get an error as in the 2nd image. When I don't type the hook in the 1st image, it's okay, but I have to. How can I solve the problem?

In the 3rd image my package.json file.

1.photo https://prnt.sc/vois5x

2.photo https://prnt.sc/voiodz

3.photo https://prnt.sc/voison

**Comment by wcandillon** [comment]
@sabriyasar I'm closing this issue as it seems unrelated to redash
