### ISSUE TITLE
withBouncing() crashes the app

### ISSUE THREAD

**Issue by yaroslavnikiforov** [wcandillon/react-native-redash#401]
I am trying to implement a bouncing card as in one of the video lessons, using PanGestureHandler with reanimated2. But it crashes when adding withBouncing. 

"react": "16.13.1",
"react-native": "0.63.3",
"react-native-gesture-handler": "^1.8.0",
"react-native-reanimated": "^2.0.0-rc.0",
"react-native-redash": "^15.11.1"

![Simulator Screen Shot - iPhone 11 - 2020-11-26 at 22 01 58](https://user-images.githubusercontent.com/42115630/100389735-d8499400-3036-11eb-8646-7b93e348b7e3.png)

Here is a reproducible demo:
[https://github.com/yaroslavnikiforov/reanimated2](https://github.com/yaroslavnikiforov/reanimated2)

**Comment by wcandillon** [comment]
Indeed this is not working yet with alpha.8 and above, will fix it soon.

**Comment by wcandillon** [comment]
This will be fixed in v16 which is released now.
