### ISSUE TITLE
Can't catch error from getYForX

### ISSUE THREAD

**Issue by VincentQuillien** [wcandillon/react-native-redash#413]
Hi everyone,

When giving an out of bound x to getYForX it throws an error (no curve found at x) but it won't be caught in a try catch block.
```ts
    const y = useDerivedValue(() => {
        try {
            return getYForX(path, 50000);
        } catch (e) {
            // the error is never caught and bubbles up to the top
            return 0;
        }
    });
```
It's probably better to check if x isn't out of bounds before calling getYForX but it is still weird I can't catch it at all.

redash: 16.0.4
reanimated: 2.0.0-rc.1

**Comment by caiphaav** [comment]
same issue

**Comment by iagormoraes** [comment]
same happened to me and the problem seems to be at `selectCurve` function where it checks if `c.curve` is null and when it is it return that error giving a crash in the app.

**Comment by forster007** [comment]
Where is the owner of that?

**Comment by wcandillon** [comment]
Woah indeed throwing an error was not clever in the context of worklets. It now returns null instead. I hope this helps.
