### ISSUE TITLE
Error after upgrading to Reanimated 2.1.0

### ISSUE THREAD

**Issue by beetlebum** [wcandillon/react-native-redash#429]
`Unable to resolve module react-native-reanimated/src/derived/interpolate from /node_modules/react-native-redash/lib/module/v1/Colors.js:`
react-native-reanimated/src/derived/interpolate could not be found within the project or in these directories:
  node_modules/react-native-redash/node_modules
  node_modules
  ../../../node_modules

**Comment by jp928** [comment]
Same error

**Comment by wcandillon** [comment]
I am trying to resolve the issue, is there a specific function that I should import to trigger this error?

**Comment by beetlebum** [comment]
works great, thank you
