### ISSUE TITLE
used react-native-redash@16.0.11 but still getting no exported member 'interpolateColor'

### ISSUE THREAD

**Issue by jbarber2016** [wcandillon/react-native-redash#452]
Using the latest redash, has this officially been removed?  I've followed alot of Williams examples where he uses interpolateColor from redash, but no longer seems to be supported.  What should I be using?

**Comment by wcandillon** [comment]
It has been removed in favor of interpolateColors from react-native-reanimated. I hope this helps?

**Comment by jbarber2016** [comment]
@wcandillon Thanks William love your videos.  You plan on ever doing the react native fashion series again?

**Comment by jbarber2016** [comment]
@wcandillon do you have any examples of using interpolateColors?  I see that according to the documentation that it returns Animated.Node, which you can't directly assign to a style.  Do I have to use an animated style?
