### ISSUE TITLE
Incompatible skew transformation types

### ISSUE THREAD

**Issue by vicrac** [wcandillon/react-native-redash#463]
RN defines skew transformations in terms of strings (SDK 42):
<img width="256" alt="Zrzut ekranu 2021-08-12 o 17 45 56" src="https://user-images.githubusercontent.com/26183214/129227150-d47b5309-f8e7-4b54-ac72-ffe3a198abe2.png">

However redash passes it as numbers: https://github.com/wcandillon/react-native-redash/blob/fd0b0ddb3b4c10ae88cf1f8a95890c7c5eb3c475/src/Matrix3.ts#L24

This resolves in a type error. Should it be changed?

**Comment by wcandillon** [comment]
Indeed I can update it, can you give me an example usage of these types so I can add a use case for it maybe?

**Comment by vicrac** [comment]
I run into it while following your tutorial on "pinch-to-zoom". Here's my code:
```tsx
<PinchGestureHandler {...gestureHandler}>
  <Animated.View
    style={{ width: width - 2 * globalStyles.appContainer.padding, zIndex }}
  >
    <Animated.Image
      source={{ uri: image }}
      style={[
        styles.image,
        { transform: transformOrigin(origin, { scale }) },
      ]}
    />
  </Animated.View>
</PinchGestureHandler>
```

**Comment by vicrac** [comment]
@wcandillon can you provide an estimate on when can this be fixed?
