### ISSUE TITLE
Control animation state

### ISSUE THREAD

**Issue by terrysahaidak** [wcandillon/react-native-redash#48]
I love the declarative approach reanimated uses do describe an animation. Declarative is cool. But sometimes you need to change the state of animation or even run it after pressing some button in the UI.

I want to open this discussion which aims to find the best solution for mixing declarative and imperative styles to work for better 60fps animations in our applications.

I'm often using some kind of state variable for this.

For example, here is the Input component, which shows a "Cancel" (just like ios default search input does) button on focus.

```js
const UNSET = -1;
const INIT = 0;
const FALSE = 0;
const TRUE = 1;

class Input extends React.Component {
  _inputRef = React.createRef();

  _inputClock = new A.Clock();
  _focusState = new A.Value(UNSET);

  _marginRight = A.cond(
    A.eq(this._focusState, TRUE),
    runTiming(this._inputClock, 8, 84),
    A.cond(
      A.eq(this._focusState, FALSE),
      runTiming(this._inputClock, 84, 8),
      8,
    ),
  );

  _translateX = A.interpolate(this._marginRight, {
    inputRange: [8, 84],
    outputRange: [100, -24],
    extrapolate: A.Extrapolate.CLAMP,
  });

  handleFocus() {
    this._focusState.setValue(TRUE);
  }

  handleBlur(shouldBlur) {
    if (shouldBlur) {
      this._inputRef.current._component.blur();
    }

    this._focusState.setValue(FALSE);
  }

  render() {
    return (
      <View style={styles.inputContainer}>
        <AnimatedTextInput
          ref={this._inputRef}
          onFocus={() => this.handleFocus()}
          onBlur={() => this.handleBlur()}
          style={[styles.input, { marginRight: this._marginRight }]}
        />
        <A.View
          style={[
            styles.cancelButton,
            { transform: [{ translateX: this._translateX }] },
          ]}
        >
          <TouchableOpacity onPress={() => this.handleBlur(true)}>
            <Text style={styles.cancel}>Cancel</Text>
          </TouchableOpacity>
        </A.View>
      </View>
    );
  }
}
```

It introduces a `focusState` variable which determinates a state of our input focus and a condition where we trigger some animation after state has been changed.

I wonder if there any other better way to do the same. Or if it's not we should introduce some sort of helper function to do that really quickly and `redash` is the right place to do it, I think.

**Comment by wcandillon** [comment]
Hey @terrysahaidak  🙋🏼‍♂️What kind of utility function do you have in mind?

**Comment by terrysahaidak** [comment]
I'm still thinking about it.

Really want to hear @wcandillon your solution over the cause I've described above. How would you implement animation on depending focus?

**Comment by felippepuhle** [comment]
@terrysahaidak @wcandillon `useTransition` solves this, I think we can close this issue

**Comment by wcandillon** [comment]
Closing for now indeed, feel free to reopen if needed.

**Comment by vamshi9666** [comment]
useTansition is a hook. what about class component ?
