### ISSUE TITLE
 ERROR  TypeError: undefined is not a function (near '...(0, _reactNativeRedash.withSpringTransition)...')

### ISSUE THREAD

**Issue by mamonaabdullah122** [wcandillon/react-native-redash#498]
My code:
const zoom = useRef(new Animated.Value(0));
const zoomAnimation = withSpringTransition(zoom.current, {
   ...SpringUtils.makeDefaultConfig(),
   overshootClamping: true,
   damping: new Animated.Value(20),
});
useCode(() => cond(eq(zoom.current, 0), set(zoom.current, 1)), []);

**Comment by FatimaAbdullah122** [comment]
I have the same issue any solution????????

**Comment by Zainab-Git** [comment]
I have the same issue toooooooooo

**Comment by mamonaabdullah122** [comment]
Hi! guys any solution please helpppppppppp!

**Comment by mamonaabdullah122** [comment]
Oh! I finally find a solution i set my react-native-redash version to 9.3.1 and it will work Thanks.

**Comment by FatimaAbdullah122** [comment]
Thanks mamonaabdullah122 you save my hours.

**Comment by Zainab-Git** [comment]
Thanks and again thanks

**Comment by mamonaabdullah122** [comment]
WELCOME
