### ISSUE TITLE
Allow passing arbitrary props like testID to the ReText TextInput component

### ISSUE THREAD

**Issue by Jyrno42** [wcandillon/react-native-redash#500]
Currently `ReText` drops additional props. Would like them to be passed on to the underlying text input instead.

**Comment by Jyrno42** [comment]
I would solve this by adding an optional prop `textInputProps?: TextInputProps;` to the component and would spread that into the rendered `AnimatedTextInput` before the `animatedProps` are spread.

If that seems ok I can create a PR for it.

**Comment by wcandillon** [comment]
yes please 🙌🏼
Also you have looking to animated text, you should definitely have a look at React Native Skia ;-)

**Comment by Jyrno42** [comment]
Will do then. 

For us ReText works perfectly since we only need to update text (a timer) based on a derived shared value. But will definitely look into Skia.
