### ISSUE TITLE
Can't import redash in non-typescript project

### ISSUE THREAD

**Issue by marcusstenbeck** [wcandillon/react-native-redash#68]
I'm developing using Expo 33, and I'm in a project that uses flow typing (can't change this).

It'll complain about running into unexpected tokens in a `.tsx` file, which is natural given that there's no compiler for TypeScript in my project. But I'm surprised that it tries to import the TypeScript files.

If I change [this line in `package.json`](https://github.com/wcandillon/react-native-redash/blob/master/package.json#L42) like the following then things work.

```diff
-   "react-native": "lib/module/index.ts",
+   "react-native": "lib/module/index.js",
```

**Comment by wcandillon** [comment]
That makes a lot of sense thks. However shouldn't a modern RN project be able to read the `ts` file normally since babel parses typescript as normal JS?

**Comment by marcusstenbeck** [comment]
> However shouldn't a modern RN project be able to read the ts file normally since babel parses typescript as normal JS?

I'm not sure. Maybe?

This is the first time I'm running into this issue, and I'm on Babel 7. However, this repo is a monorepo that contains legacy React dating back to mixin days so "modern standards" are adopted quite slowly. Unfortunately for me there's no way of "opting out" of this in the project. I really want to use redash though, if possible.

**Comment by wcandillon** [comment]
This is fair, I will update it.

**Comment by wcandillon** [comment]
This is fixed now.
