### ISSUE TITLE
Interactable component missing in doc

### ISSUE THREAD

**Issue by PierreCapo** [wcandillon/react-native-redash#71]
Hello William!

I've seen on one of your video that you use `Interactable` from redash, but I'm not seeing it mentionned anywhere in the doc? I think it would be cool to have that component explained in the readme instead of having to dig into the code.

Good job for this great library!

**Comment by dsznajder** [comment]
@PierreCapo It is missing on purpouse, because we do not have possibility to support issues related to this one

**Comment by PierreCapo** [comment]
Thanks for the answer :)

**Comment by vamshi9666** [comment]
any ways to use it or similar component ?
