### ISSUE TITLE
preserveOffset jitter with bbc-iplayer

### ISSUE THREAD

**Issue by StuartGough7** [wcandillon/react-native-redash#76]
Hi William. I ran into an issue with the bbc-iplayer in your can-it-be-done-in-react-native series where short taps on the gesture handler would result in an in-determinant position. I tried setting the PanGestureHandler to have a minDist of 5 however this did not do anything.

Diving deeper into the redash library I noticed that preserveOffset was setting offset based on Gesture state being GestureState.BEGAN. Changing this to the below meant that the power of the gesture handler could be used to circumvent the jitter and in-determinant state:

```
export const preserveOffset = (
  value: Animated.Adaptable<number>,
  state: Animated.Adaptable<GestureState>,
) => {
  const previous = new Value(0)
  const offset = new Value(0)

  return block([
    cond(
      eq(state, GestureState.ACTIVE),
      [set(offset, add(offset, sub(value, previous))), set(previous, value)],
      [set(previous, 0)],
    ),
    offset,
  ])
}

```

Hope this helps someone.

**Comment by wcandillon** [comment]
Woah thks man! I am unable to reproduce the jittery behavior. I also used your version of the function and didn't notice any differences in the behavior. Could you help me to reproduce the jittery behavior? A small screen recording would be great too.

**Comment by StuartGough7** [comment]
No worries! Thank you for the awesome animations in general, they have been incredible! If you were using the simulator it wont reproduce the error. I had it on a device (android although I dont believe the gesture responeder would be different in this case).

 Quick taps and not swipes (especially on the album artwork section) cause the whole thing to shift a little and not spring back to its desired index.

A bit of digging into your redash library and react-native-gesture-handler showed it was to do with the state and when the offset was preserved.

From the [docs](https://kmagiera.github.io/react-native-gesture-handler/docs/state.html):
>UNDETERMINED -> BEGAN ------> ACTIVE ------> END -> UNDETERMINED

If you use GestureState.ACTIVE to preserve Offset instead of BEGAN you can leverage the react-native-gesture-handler props for some more control where the state changes are more meanignful to redash ie something like:

```
<PanGestureHandler
    minDist={5}
    activeOffsetX=(-10,10) // just an example
    activeOffsetY=(-5,5) // just an example
    onGestureEvent={this._onPanGestureEvent}>
>...
```

**Comment by wcandillon** [comment]
Thanks @StuartGough7 I'm able to reproduce the behavior you describe. And indeed using `ACTIVE` will enable us to leverage things like `activeOffsetX`. 🙌🏻
