### ISSUE TITLE
Hex color

### ISSUE THREAD

**Issue by felippepuhle** [wcandillon/react-native-redash#88]
Any possibility of adding interpolation for hex colors?
I can help with this.

**Comment by jacobarvidsson** [comment]
`
import Animated from "react-native-reanimated";
import {  bInterpolateColor } from "react-native-redash";

const colorRegex = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i;
const white = { r: 255, g: 255, b: 255 };

export const hexToRgb = (hex: string) => {
  const result = colorRegex.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : white;
};

export const bHexInterpolateColors = (
  animationValue: Animated.Adaptable<number>,
  from: string,
  to: string,
): Animated.Node<any> =>
  bInterpolate(animationValue, hexToRgb(from), hexToRgb(to));
`

**Comment by dsznajder** [comment]
@felippepuhle This shouldn't be hard :) If you have some free time just add it as an option to [color interpolator](https://github.com/wcandillon/react-native-redash/blob/92e41b8fffeab077b2c351c0ef0fd94f27f10df0/src/Colors.ts#L170)

I can handle it but over the weekend :)

**Comment by felippepuhle** [comment]
I can tackle this, want to contribute a little =]
