### ISSUE TITLE
Can I disable move right/left for Interacrtable component?

### ISSUE THREAD

**Issue by sinodko** [wcandillon/react-native-redash#91]
I would like to ask you if there is any way to disable for example left swipe gesture for Interactable component.

I'm implementing this "swipeable" list rows and I would like to achieve only "one directional swipe gesture" lets say swipe right (Buttons are hidden and located only on the left side). However, in my current implemenetation I'm able to drag the row and swipe it to both sides which in my case makes no sense if there isn't anything on the other side.

Enclosing my current implementation of Interactable component

    <Interactable
          horizontalOnly={true}
          snapPoints={[
            {
              x: 100,
              damping: 1 - DAMPING,
              tension: TENSION
            },
            {
              x: 0,
              damping: 1 - DAMPING,
              tension: TENSION
            }
          ]}
          animatedValueX={this._deltaX}
        >
          <View style={{ left: 0, right: 0 }}>{children}</View>
    </Interactable>

Hope I described it well enough for understanding :( 

Thank you so much for any help!

**Comment by sinodko** [comment]
I've found that i can use `boundaries` prop. @wcandillon whats up with Interactable component? I cant find it in the most recent release.

**Comment by wcandillon** [comment]
@sebinq I removed it because we were not able to support it. However, v8 now has a withSpring() functions that provide what you need (snappoint, offsets etc).

**Comment by sebinq** [comment]
@wcandillon I've just finished your course and now searching for some old problems that I wasn't able to solve at the time to practice what I've just learned. Thank you so much!

**Comment by wcandillon** [comment]
Yes please let me know if you have any questions/suggestions. Thank you so much for the sub! Some really cool stuff coming soon on that topic.
