### ISSUE TITLE
Is there a way to re-render an Interactable component ?

### ISSUE THREAD

**Issue by vikjovanov** [wcandillon/react-native-redash#94]
Hi,

I'm using an Interactable Component as a Slider.
So I put a default position for my cursor and I wanted to know if there is a way, when I update my parent component, to reset cursor position to its default position? 
Like 'extraData' for flatList?

Thank you for any help !

**Comment by dsznajder** [comment]
@vikjovanov Yeah, you can just change `key` prop on some action and React will handle it for you.
